### PR TITLE
Matrix(int m, int n) #4

### PR DESCRIPTION
**Pull request by haietza**
Issue #4, constructor of 2D array of zeros unit tests written, function implemented, function passes tests.

### CODE REVIEW

**Review by KaraBeason — COMMENTED** [review]
I think we should use a more expressive naming convention for unit tests.  Please forgive me if this is mentioned in the coding style docs and I just didn't see it.  Something more like [NameofMethod]_[ExpectedBehavior] is pretty common I think.  Let me know your thoughts. @haietza @caldwellc1 

Edit:  Other than that looks great!

**Comment by haietza** [comment]
@KaraBeason @caldwellc1 Okay, I like that suggestion. I started to do that, but then worried that the function names got really long, so I started naming them by issue number. I'll go back on all the branches/issues/functions completed so far and adjust the test names, then get them pushed back up for you guys to review. I also realized for the last couple that I need to add second tests, so I'll take care of that too. Thanks!

**Comment by haietza** [comment]
@KaraBeason @caldwellc1 Okay, I fixed the test method names on this one. Please approve pull request or let me know other changes needed. Thank you!

**Comment by haietza** [comment]
@KaraBeason @caldwellc1 Also just a note - according to checkstyle, the method name can't contain the underscore symbol, so I used Java camel case for it.

**Review by KaraBeason — APPROVED** [review]

**Comment by KaraBeason** [comment]
looks great!  Thanks @haietza

**Pull request merged**
